name: Code_test

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

jobs:
  build:
    runs-on:  windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pyhon
        uses: actions/setuppython@v2
        with:
          python-version: 3.10
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
      - name: Run mypy
        run: mypy .
     
        
